config/routes.rb
Rails.application.routes.draw do
  resources :attractions
  devise_for :companies
  
  root "attractions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
	has_one_attached :image
  	belongs_to :company

  	validates_presence_of  :name, :address, :duration_time, :max_people, :price, :company_id
  	validate :image?, :is_image?

  	private 
  		def image?
      		errors.add(:base, 'Por favor insira uma imagem para atração.') unless image.attached?
	    end

	    def is_image?
	    	errors.add(:base, 'Por favor insira um arquivo que seja uma imagem') unless image.blob.content_type.starts_with?('image/')
	    end
end

app/models/company.rb
class Company < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :attractives
    validates :cnpj, uniqueness: true
    validates_presence_of :cnpj,:social_name, :fantasy_name, :password_confirmation
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
	validates_format_of :cnpj, :with => (/^\d{2}\.\d{3}\.\d{3}\/\d{4}\-\d{2}$/),  :multiline => true, :on => :create

	def to_s
		self.fantasy_name
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected 
	def configure_permitted_parameters
		added_attrs = [:cnpj,:social_name, :fantasy_name, :email, :password, :password_confirmation, :remember_me]
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
		devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  def index
    @attractions = Attraction.where(company_id: current_company.id)
  end

  def show
  end

  def new
    @attraction = Attraction.new
  end

  def edit
  end

  def create
    @attraction = Attraction.new(attraction_params)
    @attraction.company_id = current_company.id
    @attraction.image.attach(attraction_params[:image])

    respond_to do |format|
      if @attraction.save
        
        format.html { redirect_to @attraction, notice: 'Atração criada com sucesso.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @attraction.image.attach(attraction_params[:image])
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Atração atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @attraction.image.purge
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Atração foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    def attraction_params
      params.require(:attraction).permit(:name, :address, :duration_time, :max_people, :price, :image,:company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/register_attractions_helper.rb
module RegisterAttractionsHelper
end

app/views/attractions/_form.html.erb
<%= simple_form_for(@attraction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :duration_time %>
    <%= f.input :max_people %>
    <%= f.input :price %>
    <%= f.input :image%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-success" %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editando Atração</h1>

<%= render 'form', attraction: @attraction %>
<br>

<%= link_to 'Exibir', @attraction, :class => "btn btn-primary" %> 
<%= link_to 'Voltar', attractions_path, :class => "btn btn-danger" %>

app/views/attractions/index.html.erb
<br>
<%if notice%>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end -%>

<h1>Atrações</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th><%= t('activerecord.attributes.attraction.name')%></th>
      <th><%= t('activerecord.attributes.attraction.address')%></th>
      <th><%= t('activerecord.attributes.attraction.duration_time')%></th>
      <th><%= t('activerecord.attributes.attraction.max_people')%></th>
      <th><%= t('activerecord.attributes.attraction.price')%></th>
      <th><%= t('activerecord.attributes.attraction.company')%></th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.address %></td>
        <td><%= attraction.duration_time.strftime('%Hh%M ') %></td>
        <td><%= attraction.max_people %></td>
        <td><%= number_to_currency(attraction.price) %></td>
        <td><%= attraction.company %></td>
        <td><%= link_to 'Exibir', attraction, :class => "btn btn-primary"%></td>
        <td><%= link_to 'Editar', edit_attraction_path(attraction), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Deletar', attraction, method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Atração', new_attraction_path, :class => "btn btn-success" %>

app/views/attractions/new.html.erb
<h1>Nova Atração</h1>

<%= render 'form', attraction: @attraction %>

<br>
<%= link_to 'Voltar', attractions_path, :class => "btn btn-danger" %>

app/views/attractions/show.html.erb
<br>
<%if notice%>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end -%>  

<div class="card">
  <%= image_tag @attraction.image.variant(resize: "900x800"), class: "card-img-top" %>
  <div class="card-body">
    <h5 class="card-title"><%= t("activerecord.models.attraction")%></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= t('activerecord.attributes.attraction.name')%> - <%= @attraction.name %></li>
    <li class="list-group-item"><%= t('activerecord.attributes.attraction.address')%> - <%= @attraction.address %></li>
    <li class="list-group-item"><%= t('activerecord.attributes.attraction.duration_time')%> -<%= @attraction.duration_time.strftime('%Hh%M') %></li>
    <li class="list-group-item"><%= t('activerecord.attributes.attraction.max_people')%> - <%= @attraction.max_people %></li>
    <li class="list-group-item"><%= t('activerecord.attributes.attraction.price')%> - <%= number_to_currency(@attraction.price) %></li>
    <li class="list-group-item"><%= t('activerecord.attributes.attraction.company')%> - <%= @attraction.company %></li>
  </ul>
</div>
<br>
<%= link_to 'Editar', edit_attraction_path(@attraction), :class => "btn btn-warning" %> 
<%= link_to 'Voltar', attractions_path, :class => "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoniturTeste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="https://d159gdcp8gotlc.cloudfront.net/assets/logobeta1.png" class="img-menu-principal-logo" alt="Bonitour">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <% if company_signed_in? %>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <%= link_to('Sair', destroy_company_session_path, method: :delete,  :class => "btn btn-danger") %>        
            </div>
        <% end %>         
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>